### ISSUE TITLE
Correct manual labels for spinal cord and discs

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/pediatric-template#5]
Done in https://github.com/neuropoly/data-management/issues/248

**Comment by jcohenadad** [comment]
Reopening because the wrong files were uploaded on git-annex-- see: https://github.com/neuropoly/data-management/issues/248#issuecomment-1731691329

**Comment by rohanbanerjee** [comment]
Closing this issue as the git-annex issues were resolved. Check: https://github.com/neuropoly/data-management/issues/248#issuecomment-1731691329
